# Generated by Django 3.0.7 on 2020-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('contain_meat', models.BooleanField()),
                ('seafood', models.BooleanField()),
                ('hot', models.BooleanField()),
                ('noodle', models.BooleanField()),
                ('soup', models.BooleanField()),
                ('greasy', models.BooleanField()),
                ('cool', models.BooleanField()),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
